version: '3.7'

services:
  db:
    image: mongo:5
    container_name: pokemonDB
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGODB_DATABASE: nest-pokemon
